//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEServerGUI.ChatServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChatServiceReference.IChatServiceContract")]
    public interface IChatServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServiceContract/GetChatMessages", ReplyAction="http://tempuri.org/IChatServiceContract/GetChatMessagesResponse")]
        System.Collections.Generic.List<string> GetChatMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServiceContract/SendPrivateChatMessage", ReplyAction="http://tempuri.org/IChatServiceContract/SendPrivateChatMessageResponse")]
        void SendPrivateChatMessage(ulong remoteUserId, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChatServiceContract/SendPublicChatMessage", ReplyAction="http://tempuri.org/IChatServiceContract/SendPublicChatMessageResponse")]
        void SendPublicChatMessage(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceContractChannel : SEServerGUI.ChatServiceReference.IChatServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceContractClient : System.ServiceModel.ClientBase<SEServerGUI.ChatServiceReference.IChatServiceContract>, SEServerGUI.ChatServiceReference.IChatServiceContract {
        
        public ChatServiceContractClient() {
        }
        
        public ChatServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChatServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetChatMessages() {
            return base.Channel.GetChatMessages();
        }
        
        public void SendPrivateChatMessage(ulong remoteUserId, string message) {
            base.Channel.SendPrivateChatMessage(remoteUserId, message);
        }
        
        public void SendPublicChatMessage(string message) {
            base.Channel.SendPublicChatMessage(message);
        }
    }
}
