//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEServerGUI.ServerServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServerServiceReference.IServerServiceContract")]
    public interface IServerServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServiceContract/StartServer", ReplyAction="http://tempuri.org/IServerServiceContract/StartServerResponse")]
        void StartServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServiceContract/StopServer", ReplyAction="http://tempuri.org/IServerServiceContract/StopServerResponse")]
        void StopServer();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServiceContract/LoadServerConfig", ReplyAction="http://tempuri.org/IServerServiceContract/LoadServerConfigResponse")]
        void LoadServerConfig();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerServiceContract/SaveServerConfig", ReplyAction="http://tempuri.org/IServerServiceContract/SaveServerConfigResponse")]
        void SaveServerConfig();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServerServiceContractChannel : SEServerGUI.ServerServiceReference.IServerServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerServiceContractClient : System.ServiceModel.ClientBase<SEServerGUI.ServerServiceReference.IServerServiceContract>, SEServerGUI.ServerServiceReference.IServerServiceContract {
        
        public ServerServiceContractClient() {
        }
        
        public ServerServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartServer() {
            base.Channel.StartServer();
        }
        
        public void StopServer() {
            base.Channel.StopServer();
        }
        
        public void LoadServerConfig() {
            base.Channel.LoadServerConfig();
        }
        
        public void SaveServerConfig() {
            base.Channel.SaveServerConfig();
        }
    }
}
