//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEServerGUI.PluginServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PluginServiceReference.IPluginServiceContract")]
    public interface IPluginServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPluginServiceContract/GetPluginGuids", ReplyAction="http://tempuri.org/IPluginServiceContract/GetPluginGuidsResponse")]
        System.Collections.Generic.List<System.Guid> GetPluginGuids();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPluginServiceContract/GetPluginStatus", ReplyAction="http://tempuri.org/IPluginServiceContract/GetPluginStatusResponse")]
        bool GetPluginStatus(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPluginServiceContract/LoadPlugin", ReplyAction="http://tempuri.org/IPluginServiceContract/LoadPluginResponse")]
        void LoadPlugin(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPluginServiceContract/UnloadPlugin", ReplyAction="http://tempuri.org/IPluginServiceContract/UnloadPluginResponse")]
        void UnloadPlugin(System.Guid guid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPluginServiceContractChannel : SEServerGUI.PluginServiceReference.IPluginServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PluginServiceContractClient : System.ServiceModel.ClientBase<SEServerGUI.PluginServiceReference.IPluginServiceContract>, SEServerGUI.PluginServiceReference.IPluginServiceContract {
        
        public PluginServiceContractClient() {
        }
        
        public PluginServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PluginServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PluginServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PluginServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<System.Guid> GetPluginGuids() {
            return base.Channel.GetPluginGuids();
        }
        
        public bool GetPluginStatus(System.Guid guid) {
            return base.Channel.GetPluginStatus(guid);
        }
        
        public void LoadPlugin(System.Guid guid) {
            base.Channel.LoadPlugin(guid);
        }
        
        public void UnloadPlugin(System.Guid guid) {
            base.Channel.UnloadPlugin(guid);
        }
    }
}
