//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;
using System;

using SEModAPIInternal.API.Entity;

namespace SEServerGUI.ServiceReference
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IInternalServiceContract")]
    public interface IInternalServiceContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServiceContract/GetConnectedPlayers", ReplyAction="http://tempuri.org/IInternalServiceContract/GetConnectedPlayersResponse")]
        System.Collections.Generic.List<ulong> GetConnectedPlayers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInternalServiceContract/GetSectorEntities", ReplyAction="http://tempuri.org/IInternalServiceContract/GetSectorEntitiesResponse")]
        System.Collections.Generic.List<BaseEntity> GetSectorEntities();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInternalServiceContractChannel : IInternalServiceContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InternalServiceContractClient : System.ServiceModel.ClientBase<IInternalServiceContract>, IInternalServiceContract {
        
        public InternalServiceContractClient() {
        }
        
        public InternalServiceContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InternalServiceContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InternalServiceContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ulong> GetConnectedPlayers() {
            return base.Channel.GetConnectedPlayers();
        }
        
        public System.Collections.Generic.List<BaseEntity> GetSectorEntities() {
            return base.Channel.GetSectorEntities();
        }
    }
}
